"""Notification model — proactive in-app notifications.

Unlike the audit_log-derived "activity feed", notifications stored here are
generated by background scans (deadlines approaching, missing required data,
anomalies detected, validations pending) and are designed for proactive UX —
the bell icon, the email digest, etc.
"""
from typing import TYPE_CHECKING, Optional
from datetime import datetime
from uuid import UUID
import enum

from sqlalchemy import String, Text, Boolean, DateTime, ForeignKey, Index
from sqlalchemy.dialects.postgresql import JSON, UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TenantMixin, UUIDMixin, TimestampMixin

if TYPE_CHECKING:
    from app.models.user import User


class NotificationType(str, enum.Enum):
    """Categories of notifications. Keep small and meaningful."""
    DEADLINE = "deadline"                # Compliance / CSRD / BEGES deadline approaching
    MISSING_DATA = "missing_data"        # Required datapoint not yet entered
    VALIDATION = "validation"            # Data entry awaiting approval
    ANOMALY = "anomaly"                  # ML / rule-based anomaly detected
    BILLING = "billing"                  # Trial ending, payment failed, quota approaching
    SYSTEM = "system"                    # Maintenance, release notes
    INVITATION = "invitation"            # Team invitation accepted / pending


class NotificationPriority(str, enum.Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    URGENT = "urgent"


class Notification(Base, UUIDMixin, TenantMixin, TimestampMixin):
    """A single notification destined for one user (or the whole tenant)."""

    __tablename__ = "notifications"

    # Recipient (null user_id means "all tenant admins")
    user_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="CASCADE"),
        nullable=True, index=True,
    )

    # Content
    type: Mapped[str] = mapped_column(String(30), nullable=False, index=True)
    priority: Mapped[str] = mapped_column(
        String(10), nullable=False, default="medium", server_default="medium"
    )
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    body: Mapped[Optional[str]] = mapped_column(Text, nullable=True)
    link: Mapped[Optional[str]] = mapped_column(String(500), nullable=True)

    # Lifecycle
    read_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    dismissed_at: Mapped[Optional[datetime]] = mapped_column(DateTime(timezone=True), nullable=True)
    expires_at: Mapped[Optional[datetime]] = mapped_column(
        DateTime(timezone=True), nullable=True,
        comment="Optional: auto-hide after this date (e.g. deadline passed)."
    )

    # Dedupe key — used by the proactive scanner to avoid creating duplicate
    # notifications for the same condition. Example: "deadline:csrd:2027-04-30"
    dedupe_key: Mapped[Optional[str]] = mapped_column(
        String(255), nullable=True, index=True,
        comment="Unique key per (tenant, condition). Idempotent creation."
    )

    # Optional structured payload (e.g. {"days_left": 30, "regulation": "csrd"})
    metadata_json: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True)

    # Relationships
    user: Mapped[Optional["User"]] = relationship("User", foreign_keys=[user_id])

    __table_args__ = (
        Index("idx_notif_tenant_user", "tenant_id", "user_id"),
        Index("idx_notif_tenant_unread", "tenant_id", "read_at"),
        Index("idx_notif_dedupe", "tenant_id", "dedupe_key"),
    )

    @property
    def is_read(self) -> bool:
        return self.read_at is not None

    @property
    def is_dismissed(self) -> bool:
        return self.dismissed_at is not None
