"""
Report History — track every generated report (metadata only, file is regenerated on demand).
"""
from typing import TYPE_CHECKING, Optional
from uuid import UUID
from datetime import datetime

from sqlalchemy import String, Integer, JSON, ForeignKey, Text
from sqlalchemy.dialects.postgresql import UUID as PGUUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base, TenantMixin, TimestampMixin, UUIDMixin

if TYPE_CHECKING:
    from app.models.tenant import Tenant
    from app.models.user import User


class ReportHistory(Base, UUIDMixin, TenantMixin, TimestampMixin):
    """Audit + reusability log of every report the tenant has generated."""

    __tablename__ = "report_history"

    report_type: Mapped[str] = mapped_column(String(50), nullable=False, comment="csrd, sfdr, executive, gri, tcfd, ...")
    format: Mapped[str] = mapped_column(String(10), nullable=False, comment="pdf, excel, word, json")
    period: Mapped[str] = mapped_column(String(20), nullable=False, default="annual")
    year: Mapped[Optional[int]] = mapped_column(Integer, nullable=True)
    organization_id: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("organizations.id", ondelete="SET NULL"),
        nullable=True,
    )
    generated_by: Mapped[Optional[UUID]] = mapped_column(
        PGUUID(as_uuid=True),
        ForeignKey("users.id", ondelete="SET NULL"),
        nullable=True,
    )
    file_size: Mapped[Optional[int]] = mapped_column(Integer, nullable=True, comment="Size of generated file in bytes")
    content_hash: Mapped[Optional[str]] = mapped_column(
        String(64), nullable=True, index=True,
        comment="SHA-256 hash of the original generated bytes — audit-grade integrity check",
    )
    version: Mapped[int] = mapped_column(Integer, nullable=False, default=1, comment="Auto-incremented per (tenant, report_type, year)")
    params: Mapped[Optional[dict]] = mapped_column(JSON, nullable=True, comment="Original request parameters for re-generation")

    # Sharing
    share_token: Mapped[Optional[str]] = mapped_column(
        String(64), nullable=True, unique=True, index=True,
        comment="Random URL-safe token for public download",
    )
    share_expires_at: Mapped[Optional[datetime]] = mapped_column(nullable=True)

    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    tenant: Mapped["Tenant"] = relationship("Tenant")
    user: Mapped[Optional["User"]] = relationship("User", foreign_keys=[generated_by])

    def __repr__(self) -> str:
        return f"<ReportHistory(id={self.id}, type='{self.report_type}', format='{self.format}')>"
