apiVersion: v1
kind: Service
metadata:
  name: esgplatform-frontend
  namespace: esgplatform
  labels:
    app: esgplatform-frontend
spec:
  selector:
    app: esgplatform-frontend
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  type: ClusterIP
