"""
arelle_validation_service.py — iXBRL / ESEF Validation Engine
==============================================================

Three-layer validation for iXBRL documents generated by ESGflow:

  Layer 1 — Structural  : XML well-formedness + required namespaces + iXBRL
                          element presence. Runs in < 5 ms, no network.
  Layer 2 — Semantic    : ESRS mandatory concept check against the ESGflow
                          concept catalog (esrs_taxonomy.py). Detects missing
                          obligatory disclosures. Runs in < 20 ms.
  Layer 3 — Arelle CLI  : Full XSD validation against the official EFRAG
                          taxonomy package via Arelle. Only runs if
                          ``arelle`` is installed in the Python environment.
                          Downloads taxonomy on first run (~30 MB cache).

Usage
-----
    from app.services.arelle_validation_service import validate_ixbrl
    report = await validate_ixbrl(xhtml_bytes, sections=["E1", "S1"])
    # report.passed → bool
    # report.issues → list[ValidationIssue]
    # report.summary → dict with counts

Arelle installation (optional, not required for layers 1+2):
    pip install arelle-release
    # The EFRAG taxonomy package is downloaded automatically by Arelle
    # from https://efrag.org on first use.
"""
from __future__ import annotations

import asyncio
import re
import subprocess
import sys
import tempfile
import xml.etree.ElementTree as ET
from dataclasses import dataclass, field, asdict
from typing import List, Optional
import logging

logger = logging.getLogger(__name__)

# ── ESRS mandatory concepts (from our catalog) ─────────────────────────────
try:
    from app.services.esrs_taxonomy import all_concepts, ESRS_NS
    _MANDATORY_CONCEPTS = {c.concept_id for c in all_concepts() if c.required}
    _ALL_CONCEPT_IDS    = {c.concept_id for c in all_concepts()}
    _ESRS_NS = ESRS_NS
except Exception:
    _MANDATORY_CONCEPTS = set()
    _ALL_CONCEPT_IDS    = set()
    _ESRS_NS = "https://xbrl.efrag.org/taxonomy/esrs/2024-12-31/esrs_cor"

# Required namespaces in a valid iXBRL/ESEF document
_REQUIRED_NS = {
    "ix":    "http://www.xbrl.org/2013/inlineXBRL",
    "xbrli": "http://www.xbrl.org/2003/instance",
    "link":  "http://www.xbrl.org/2003/linkbase",
    "esrs":  _ESRS_NS,
}

# iXBRL structural patterns we look for
_IX_NON_FRACTION_RE = re.compile(r'<ix:nonFraction\b', re.IGNORECASE)
_IX_NON_NUMERIC_RE  = re.compile(r'<ix:nonNumeric\b',  re.IGNORECASE)
_IX_HEADER_RE       = re.compile(r'<ix:header\b',      re.IGNORECASE)
_IX_CONTEXT_RE      = re.compile(r'<xbrli:context\b',  re.IGNORECASE)
_CONCEPT_NAME_RE    = re.compile(r'name="([^"]+)"')


# ── Data classes ───────────────────────────────────────────────────────────

@dataclass
class ValidationIssue:
    severity:  str   # "error" | "warning" | "info"
    layer:     str   # "structural" | "semantic" | "arelle"
    message:   str
    concept:   Optional[str] = None
    rule:      Optional[str] = None

    def to_dict(self) -> dict:
        return asdict(self)


@dataclass
class ValidationReport:
    passed:       bool
    layers_run:   List[str]
    issues:       List[ValidationIssue] = field(default_factory=list)
    arelle_available: bool = False
    arelle_version:   Optional[str] = None

    # ── convenience ---
    @property
    def errors(self) -> List[ValidationIssue]:
        return [i for i in self.issues if i.severity == "error"]

    @property
    def warnings(self) -> List[ValidationIssue]:
        return [i for i in self.issues if i.severity == "warning"]

    @property
    def summary(self) -> dict:
        return {
            "passed":      self.passed,
            "layers_run":  self.layers_run,
            "total":       len(self.issues),
            "errors":      len(self.errors),
            "warnings":    len(self.warnings),
            "infos":       len([i for i in self.issues if i.severity == "info"]),
            "arelle_available": self.arelle_available,
            "arelle_version":   self.arelle_version,
        }

    def to_dict(self) -> dict:
        return {
            "passed":            self.passed,
            "layers_run":        self.layers_run,
            "arelle_available":  self.arelle_available,
            "arelle_version":    self.arelle_version,
            "summary":           self.summary,
            "issues":            [i.to_dict() for i in self.issues],
        }


# ── Layer 1 : Structural validation ───────────────────────────────────────

def _validate_structural(raw: bytes) -> List[ValidationIssue]:
    """
    Layer 1: Fast structural checks — no network, < 5 ms.
    Validates:
      - UTF-8 decodable
      - Valid XML (parse check)
      - Required iXBRL / XBRL namespaces declared
      - <ix:header> present
      - At least one <xbrli:context> defined
      - At least one <ix:nonFraction> or <ix:nonNumeric> tagged fact
    """
    issues: List[ValidationIssue] = []
    text: str

    # 1a. UTF-8 decoding
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError as exc:
        issues.append(ValidationIssue(
            severity="error", layer="structural",
            message=f"Le document n'est pas encodé en UTF-8 : {exc}",
            rule="ESEF-UTF8",
        ))
        return issues

    # 1b. XML well-formedness
    try:
        ET.fromstring(raw)
    except ET.ParseError as exc:
        issues.append(ValidationIssue(
            severity="error", layer="structural",
            message=f"XML malformé : {exc}",
            rule="XML-WF",
        ))
        return issues  # Cannot continue if XML is broken

    # 1c. Required namespaces
    for prefix, uri in _REQUIRED_NS.items():
        if uri not in text:
            issues.append(ValidationIssue(
                severity="error", layer="structural",
                message=f"Espace de noms obligatoire manquant : {prefix} ({uri})",
                rule=f"NS-{prefix.upper()}",
            ))

    # 1d. iXBRL header
    if not _IX_HEADER_RE.search(text):
        issues.append(ValidationIssue(
            severity="error", layer="structural",
            message="Élément <ix:header> absent — le document n'est pas un iXBRL valide.",
            rule="IX-HEADER",
        ))

    # 1e. XBRL contexts
    ctx_count = len(_IX_CONTEXT_RE.findall(text))
    if ctx_count == 0:
        issues.append(ValidationIssue(
            severity="error", layer="structural",
            message="Aucun contexte <xbrli:context> défini.",
            rule="XBRL-CTX",
        ))
    else:
        issues.append(ValidationIssue(
            severity="info", layer="structural",
            message=f"{ctx_count} contexte(s) XBRL trouvé(s).",
            rule="XBRL-CTX",
        ))

    # 1f. Tagged facts
    n_fraction = len(_IX_NON_FRACTION_RE.findall(text))
    n_numeric  = len(_IX_NON_NUMERIC_RE.findall(text))
    total_facts = n_fraction + n_numeric
    if total_facts == 0:
        issues.append(ValidationIssue(
            severity="error", layer="structural",
            message="Aucun fait iXBRL balisé (ni ix:nonFraction ni ix:nonNumeric).",
            rule="IX-FACTS",
        ))
    else:
        issues.append(ValidationIssue(
            severity="info", layer="structural",
            message=f"{total_facts} fait(s) iXBRL balisé(s) : {n_fraction} numériques, {n_numeric} textuels.",
            rule="IX-FACTS",
        ))

    # 1g. Schema reference
    if "esrs_cor.xsd" not in text:
        issues.append(ValidationIssue(
            severity="warning", layer="structural",
            message="Référence au schéma XSD EFRAG (esrs_cor.xsd) non trouvée dans le document.",
            rule="ESEF-SCHEMA-REF",
        ))
    else:
        issues.append(ValidationIssue(
            severity="info", layer="structural",
            message="Référence taxonomie EFRAG 2024-12-31 présente (esrs_cor.xsd).",
            rule="ESEF-SCHEMA-REF",
        ))

    return issues


# ── Layer 2 : Semantic validation ─────────────────────────────────────────

def _validate_semantic(raw: bytes, sections: Optional[List[str]] = None) -> List[ValidationIssue]:
    """
    Layer 2: ESRS semantic checks — concept catalog + mandatory disclosure check.
    Validates:
      - All concept names used in ix:nonFraction/ix:nonNumeric exist in our catalog
      - Required ESRS concepts for the requested sections are present
    """
    issues: List[ValidationIssue] = []
    if not _ALL_CONCEPT_IDS:
        issues.append(ValidationIssue(
            severity="info", layer="semantic",
            message="Catalog ESRS non chargé — validation sémantique ignorée.",
        ))
        return issues

    try:
        text = raw.decode("utf-8")
    except Exception:
        return issues

    # 2a. Find all concept names used in the document
    used_concepts: set[str] = set(_CONCEPT_NAME_RE.findall(text))

    # 2b. Filter to only ESRS concepts (ignore xbrli:context etc.)
    used_esrs = {c for c in used_concepts if ":" in c and
                 not c.startswith("xbrli:") and
                 not c.startswith("link:") and
                 not c.startswith("ix:")}

    if not used_esrs:
        issues.append(ValidationIssue(
            severity="warning", layer="semantic",
            message="Aucun concept ESRS trouvé dans le document.",
            rule="ESRS-CONCEPTS",
        ))
    else:
        issues.append(ValidationIssue(
            severity="info", layer="semantic",
            message=f"{len(used_esrs)} concept(s) ESRS balisé(s) dans le document.",
            rule="ESRS-CONCEPTS",
        ))

    # 2c. Unknown concepts (not in our catalog)
    unknown = used_esrs - _ALL_CONCEPT_IDS
    for c in sorted(unknown):
        issues.append(ValidationIssue(
            severity="warning", layer="semantic",
            message=f"Concept non reconnu dans le catalog EFRAG : {c}",
            concept=c,
            rule="ESRS-UNKNOWN-CONCEPT",
        ))

    # 2d. Missing mandatory concepts
    #     Only check mandatory concepts belonging to requested sections
    if sections:
        norm_sections = [
            s if s.upper().startswith("ESRS") else f"ESRS {s.upper()}"
            for s in sections
        ]
        from app.services.esrs_taxonomy import all_concepts as _all
        mandatory_in_scope = {
            c.concept_id for c in _all()
            if c.required and c.standard in norm_sections
        }
    else:
        mandatory_in_scope = _MANDATORY_CONCEPTS

    missing_mandatory = mandatory_in_scope - used_esrs
    for c in sorted(missing_mandatory):
        issues.append(ValidationIssue(
            severity="warning", layer="semantic",
            message=f"Concept obligatoire absent : {c}",
            concept=c,
            rule="ESRS-MANDATORY",
        ))

    if not missing_mandatory:
        issues.append(ValidationIssue(
            severity="info", layer="semantic",
            message=f"Tous les concepts obligatoires de la sélection sont présents ({len(mandatory_in_scope)}).",
            rule="ESRS-MANDATORY",
        ))

    return issues


# ── Layer 3 : Arelle validation ────────────────────────────────────────────

def _check_arelle() -> tuple[bool, Optional[str]]:
    """Return (available, version_string)."""
    try:
        result = subprocess.run(
            [sys.executable, "-m", "arelle.CntlrCmdLine", "--version"],
            capture_output=True, text=True, timeout=15,
        )
        if result.returncode == 0:
            ver = result.stdout.strip().split("\n")[0]
            return True, ver
        # Try the arelleCmdLine entry point
        result2 = subprocess.run(
            ["arelleCmdLine", "--version"],
            capture_output=True, text=True, timeout=15,
        )
        if result2.returncode == 0:
            ver = result2.stdout.strip().split("\n")[0]
            return True, ver
    except (FileNotFoundError, subprocess.TimeoutExpired, Exception):
        pass

    # Last resort: try importing
    try:
        import importlib
        arelle = importlib.import_module("arelle")
        ver = getattr(arelle, "__version__", "unknown")
        return True, f"arelle {ver} (import)"
    except ImportError:
        pass

    return False, None


def _validate_arelle(raw: bytes) -> List[ValidationIssue]:
    """
    Layer 3: Full Arelle XSD validation.
    Writes the iXBRL to a temp file and calls Arelle CLI.
    Returns [] if Arelle is not installed (not an error — layers 1+2 still ran).
    """
    issues: List[ValidationIssue] = []

    available, version = _check_arelle()
    if not available:
        issues.append(ValidationIssue(
            severity="info", layer="arelle",
            message=(
                "Arelle non installé dans l'environnement. "
                "Pour une validation XSD complète (EFRAG taxonomy), "
                "installez : pip install arelle-release"
            ),
            rule="ARELLE-UNAVAILABLE",
        ))
        return issues

    # Write to temp file
    try:
        with tempfile.NamedTemporaryFile(suffix=".xhtml", delete=False) as f:
            tmp_path = f.name
            f.write(raw)
    except Exception as exc:
        issues.append(ValidationIssue(
            severity="warning", layer="arelle",
            message=f"Impossible d'écrire le fichier temporaire : {exc}",
        ))
        return issues

    # Build Arelle command
    # --disclosureSystem efrag-esrs validates against EFRAG ESRS taxonomy
    cmd = [
        sys.executable, "-m", "arelle.CntlrCmdLine",
        "--file", tmp_path,
        "--validate",
        "--disclosureSystem", "efrag-esrs",
        "--logLevel", "WARNING",
        "--logFile", "-",   # output to stdout
    ]

    try:
        result = subprocess.run(
            cmd, capture_output=True, text=True, timeout=120,
        )
        output = (result.stdout or "") + (result.stderr or "")

        if result.returncode == 0 and not output.strip():
            issues.append(ValidationIssue(
                severity="info", layer="arelle",
                message=f"✅ Validation Arelle réussie — aucune erreur ({version}).",
                rule="ARELLE-PASS",
            ))
        else:
            # Parse Arelle output lines
            for line in output.splitlines():
                line = line.strip()
                if not line:
                    continue
                if "[ERROR]" in line or "error" in line.lower():
                    issues.append(ValidationIssue(
                        severity="error", layer="arelle",
                        message=line, rule="ARELLE-ERROR",
                    ))
                elif "[WARNING]" in line or "warning" in line.lower():
                    issues.append(ValidationIssue(
                        severity="warning", layer="arelle",
                        message=line, rule="ARELLE-WARNING",
                    ))
                else:
                    issues.append(ValidationIssue(
                        severity="info", layer="arelle",
                        message=line, rule="ARELLE-INFO",
                    ))

            if not issues:
                issues.append(ValidationIssue(
                    severity="info", layer="arelle",
                    message=f"Arelle exécuté ({version}), code retour : {result.returncode}.",
                    rule="ARELLE-DONE",
                ))
    except subprocess.TimeoutExpired:
        issues.append(ValidationIssue(
            severity="warning", layer="arelle",
            message="Timeout Arelle (120 s) — document trop volumineux ou réseau lent (téléchargement taxonomie).",
            rule="ARELLE-TIMEOUT",
        ))
    except Exception as exc:
        issues.append(ValidationIssue(
            severity="warning", layer="arelle",
            message=f"Erreur lors de l'exécution Arelle : {exc}",
        ))
    finally:
        import os
        try:
            os.unlink(tmp_path)
        except Exception:
            pass

    return issues


# ── Public API ─────────────────────────────────────────────────────────────

async def validate_ixbrl(
    raw: bytes,
    sections: Optional[List[str]] = None,
    run_arelle: bool = True,
) -> ValidationReport:
    """
    Run all three validation layers on the given iXBRL bytes.

    Parameters
    ----------
    raw         iXBRL/XHTML content as bytes
    sections    ESRS sections included (e.g. ["E1", "S1", "G1"]).
                Used for mandatory concept scoping in Layer 2.
    run_arelle  If False, skip Layer 3 even if Arelle is installed.

    Returns
    -------
    ValidationReport  with .passed, .issues, .summary, .to_dict()
    """
    layers_run: List[str] = []
    issues: List[ValidationIssue] = []

    # Layer 1 — Structural
    l1 = _validate_structural(raw)
    layers_run.append("structural")
    issues.extend(l1)

    # Layer 2 — Semantic (skip if structural errors prevent parsing)
    l1_errors = [i for i in l1 if i.severity == "error"]
    if not l1_errors or all(i.rule in ("ESEF-SCHEMA-REF",) for i in l1_errors):
        l2 = _validate_semantic(raw, sections)
        layers_run.append("semantic")
        issues.extend(l2)

    # Layer 3 — Arelle (async-safe: run in thread pool)
    arelle_available, arelle_version = False, None
    if run_arelle:
        arelle_available, arelle_version = await asyncio.get_event_loop().run_in_executor(
            None, _check_arelle
        )
        l3 = await asyncio.get_event_loop().run_in_executor(
            None, _validate_arelle, raw
        )
        layers_run.append("arelle")
        issues.extend(l3)

    # Determine overall pass/fail
    # Passed = no errors in layers 1 or 2; Arelle errors are advisory
    blocking_errors = [
        i for i in issues
        if i.severity == "error" and i.layer in ("structural", "semantic")
    ]
    passed = len(blocking_errors) == 0

    return ValidationReport(
        passed=passed,
        layers_run=layers_run,
        issues=issues,
        arelle_available=arelle_available,
        arelle_version=arelle_version,
    )
